# Generated by Django 3.2.6 on 2021-08-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('main_image', models.ImageField(upload_to='')),
                ('alt_img_tag', models.CharField(blank=True, default='', max_length=125, null=True)),
                ('description_len', models.PositiveIntegerField(blank=True, null=True)),
                ('article_category', models.CharField(choices=[('NEWS', 'NEWS'), ('DEALS', 'DEALS'), ('GUIDES', 'GUIDES'), ('REVIEWS', 'REVIEWS')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank='True', max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('author_description', models.TextField(blank='True', max_length=300, null=True)),
                ('author_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('author_fb', models.CharField(blank=True, max_length=100, null=True)),
                ('author_tw', models.CharField(blank=True, max_length=100, null=True)),
                ('author_ig', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genres', models.ManyToManyField(to='games_db.Genre')),
                ('systems', models.ManyToManyField(to='games_db.System')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_quotes', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('alt_img_tag', models.CharField(blank=True, default='', max_length=125, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_contents', to='games_db.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='games_db.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='games',
            field=models.ManyToManyField(to='games_db.Game'),
        ),
    ]
