# Generated by Django 3.2.6 on 2021-08-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0003_article_image_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='alt_img_tag',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_credit',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='alt_img_tag',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='image_credit',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
