# Generated by Django 3.2.6 on 2021-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0004_auto_20210820_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=' ', max_length=600),
            preserve_default=False,
        ),
    ]
