# Generated by Django 3.2.6 on 2021-08-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0005_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genres',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
