# Generated by Django 3.2.6 on 2021-08-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0006_article_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='genres',
        ),
    ]
