# Generated by Django 3.2.6 on 2021-08-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0008_articlestatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
