# Generated by Django 3.2.6 on 2021-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0009_delete_articlestatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
