# Generated by Django 3.2.6 on 2021-08-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
