# Generated by Django 3.2.6 on 2021-08-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0011_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
