# Generated by Django 3.2.6 on 2021-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0012_remove_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(null=True, to='games_db.Genre'),
        ),
    ]
