# Generated by Django 3.2.6 on 2021-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0013_alter_game_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
