# Generated by Django 3.2.6 on 2021-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0015_article_fb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fb_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
