# Generated by Django 3.2.6 on 2021-08-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0019_alter_game_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='games',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
