# Generated by Django 3.2.6 on 2021-08-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0024_alter_article_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
