# Generated by Django 3.2.6 on 2021-09-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0025_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='side_banner',
            field=models.BooleanField(default=False),
        ),
    ]
