# Generated by Django 3.2.6 on 2021-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0026_article_side_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='side_banner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
