# Generated by Django 3.2.6 on 2021-09-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_db', '0027_article_side_banner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='side_banner',
            field=models.BooleanField(default=True),
        ),
    ]
